re commit
CUCCS/2019-NS-Public-yangyizhou-github pull request #1
Opened 2019-09-26 17:10 UTC by yangyizhou-github

first right commit

2019-10-10 13:17 UTC, TheMasterOfMagic requested changes
有问题呀，怎么最新一次commit是删掉了所有文件？

2019-10-10 14:34 UTC, yangyizhou-github commented
> 有问题呀，怎么最新一次commit是删掉了所有文件？

之前图片格式不兼容，我先传的图片，然后在把图片链接到md文档里

2019-10-11 01:45 UTC, TheMasterOfMagic commented
> > 有问题呀，怎么最新一次commit是删掉了所有文件？
> 
> 之前图片格式不兼容，我先传的图片，然后在把图片链接到md文档里

所以把文件加回来呀，不然等于什么都没交呀

2019-10-11 02:19 UTC, yangyizhou-github commented
> > > 有问题呀，怎么最新一次commit是删掉了所有文件？
> > 
> > 
> > 之前图片格式不兼容，我先传的图片，然后在把图片链接到md文档里
> 
> 所以把文件加回来呀，不然等于什么都没交呀

base弄错了。。。我重新弄一下 不好意思

2019-10-11 02:28 UTC, closed without merging